# Generated by Django 3.0.7 on 2020-08-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
